### ISSUE TITLE
miss the document in the folder of "dump"

### ISSUE THREAD

**Issue by ZeroerWiser** [Starlien95/GraphPrompt#1]
such as "/dumps/ENZYMESPreTrain/GIN/best.pt", when running the code of "python run.py" for the nodedownstream task

**Comment by Starlien95** [comment]
After running the pretrain code, the corresponding files will be generated.

**Comment by ZeroerWiser** [comment]
你好，在节点分类这个任务上，我运行预训练的代码文件pre_train.py时，报错是utils脚本中的graphs字典数据不存在"raw"这个字段，我检查过传入utils文件夹的pretrain_load_data的graphs字典是空的


归零者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Starlien95/GraphPrompt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 晚上8:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Starlien95/GraphPrompt] miss the document in the folder of "dump" (Issue #1)





 
After running the pretrain code, the corresponding files will be generated.

**Comment by Starlien95** [comment]
是enzymes数据集的节点分类任务吗

**Comment by ZeroerWiser** [comment]
是的，默认数据集enzymes。flickr的数据集我现在正在跑。另外我想问问你们实验中，各个模型基本上准确率上下限都蛮大的，是因为数据集的原因吗？为什么考虑使用这五个数据集呢




归零者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Starlien95/GraphPrompt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 晚上8:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Starlien95/GraphPrompt] miss the document in the folder of "dump" (Issue #1)





 
是enzymes数据集的节点分类任务吗

**Comment by Starlien95** [comment]
enzymes上，图分类和节点分类使用的是同样的预训练模型。所以如果图任务是可以正常运行的，节点任务也是可以的。但我明天会再确认一下代码是否在上传过程中遗漏了什么部分，检查过后再给您答复

**Comment by ZeroerWiser** [comment]
谢谢，但是图分类这个任务我允许报错AttributeError: Can't get attribute 'DGLHeteroGraph' on <module 'dgl.heterograph'，是版本问题对吧，我已经放弃挣扎了o(╥﹏╥)o




归零者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Starlien95/GraphPrompt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Starlien95/GraphPrompt] miss the document in the folder of "dump" (Issue #1)





 
enzymes上，图分类和节点分类使用的是同样的预训练模型。所以如果图任务是可以正常运行的，节点任务也是可以的。但我明天会再确认一下代码是否在上传过程中遗漏了什么部分，检查过后再给您答复

**Comment by Starlien95** [comment]
1.我们计算的是不同tasks（比如节点分类不同的图来训练prompt就是不同的task）的mean和std，tasks之间的区别可能会比较大导致std也会比较大
2.选择数据集的时候优先考虑的是找到即有node label又有graph label的数据集。在TUDataset中我们找到了合适的数据集。Flikcr的图比较大，可以反映模型在大图上的性能，所以我们对于节点任务增加了flickr数据集

**Comment by Starlien95** [comment]
1.我们计算的是不同tasks（比如节点分类不同的图来训练prompt就是不同的task）的mean和std，tasks之间的区别可能会比较大导致std也会比较大
2.选择数据集的时候优先考虑的是找到即有node label又有graph label的数据集，这样可以在一个数据集上同时进行图级别和节点级别的任务，很适合我们的任务场景，我们在TUDataset中找到了这样的数据集。Flikcr的图比较大，可以反映模型在大图上的性能，所以我们对于节点任务增加了flickr数据集

**Comment by Starlien95** [comment]
可能是dgl的版本问题。但我会再检查一遍上传过程是否有遗漏，明天给您答复。感谢您对我们工作的关注！

**Comment by ZeroerWiser** [comment]
非常感谢，图神经网络与提示学习都是极具研究前景的前沿研究方向，祝贵团队能够硕果丰收


归零者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Starlien95/GraphPrompt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 晚上8:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Starlien95/GraphPrompt] miss the document in the folder of "dump" (Issue #1)





 
可能是dgl的版本问题。但我会再检查一遍上传过程是否有遗漏，明天给您答复。感谢您对我们工作的关注！

**Comment by Starlien95** [comment]
您好，我已经重新测试过代码，确定每个代码都可以正常运行

**Comment by ZeroerWiser** [comment]
好的


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Starlien95/GraphPrompt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 中午1:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Starlien95/GraphPrompt] miss the document in the folder of "dump" (Issue #1)





 
您好，我已经重新测试过代码，确定每个代码都可以正常运行

**Comment by Starlien95** [comment]
您遇到的问题应该可以通过手动安装dgl0.9.0解决

**Comment by ZeroerWiser** [comment]
谢谢，已跑通


归零者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Starlien95/GraphPrompt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 晚上6:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Starlien95/GraphPrompt] miss the document in the folder of "dump" (Issue #1)





 
您遇到的问题应该可以通过手动安装dgl0.9.0解决

**Comment by WxxShirley** [comment]
> 谢谢，已跑通 归零者 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Starlien95/GraphPrompt" ***@***.***&gt;; 发送时间:&nbsp;2023年3月13日(星期一) 晚上6:36 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Starlien95/GraphPrompt] miss the document in the folder of "dump" (Issue #1) 您遇到的问题应该可以通过手动安装dgl0.9.0解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以请教下您运行当前代码的结果吗？目前release的代码，我未经改动发现在GraphClasification上效果远好于论文结果；NodeClassification是NA(Prompt会得到Nan的结果从而影响了后面所有的计算)..
