### ISSUE TITLE
KeyError: 'raw'

### ISSUE THREAD

**Issue by Lylovewhy** [Starlien95/GraphPrompt#10]
Traceback (most recent call last):
  File "/home/ylin/GraphPrompt/graphdownstream/pre_train.py", line 462, in <module>
    data = pretrain_load_data(train_config["graph_dir"], train_config["graphslabel_dir"], num_workers=train_config["num_workers"])
  File "/home/ylin/GraphPrompt/graphdownstream/utils.py", line 623, in pretrain_load_data
    for g, graph in graphs["raw"].items():
KeyError: 'raw'

looking forward to your reply~

**Comment by Lylovewhy** [comment]
<img width="400" alt="微信图片_20231128193943" src="https://github.com/Starlien95/GraphPrompt/assets/130729758/ce3d76c0-3709-45e5-8764-b0ba04c05cb2">
  ../data/ENZYMES下面没有ENZYMESPreTrain，只有../data下有ENZYMESPreTrain

**Comment by SwaggyZhang** [comment]
> <img alt="微信图片_20231128193943" width="400" src="https://private-user-images.githubusercontent.com/130729758/286237352-ce3d76c0-3709-45e5-8764-b0ba04c05cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDY2MzcsIm5iZiI6MTcwMTI0NjMzNywicGF0aCI6Ii8xMzA3Mjk3NTgvMjg2MjM3MzUyLWNlM2Q3NmMwLTM3MDktNDVlNS04NzY0LWIwYmEwNGMwNWNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwODI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzExYjVmMGNkZGU3MWVjYWM5MTZhZDZjMjIxNmE0N2Y4MTljYTliMDYwMjMxNTkxOTMxODA5MjdlZmNhYmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xmuZDu8l_MTwbJnjCL2FkPuaB6hSG80kgWk0AhmF3lg"> ../data/ENZYMES下面没有ENZYMESPreTrain，只有../data下有ENZYMESPreTrain

你好，我也在follow这篇工作，此处应该是一个笔误，仅需把这个ENZYMESPreTrain移动到ENZYMES文件夹下就可以了，如果帮助到你，希望能和你一起讨论~

**Comment by Starlien95** [comment]
您只需要调整对应文件夹的位置即可，同时我们重新上传了代码
