### ISSUE TITLE
About parameters 

### ISSUE THREAD

**Issue by jiaruHithub** [Starlien95/GraphPrompt#3]
Thanks for released code and ouperformed work!
When using ```graph_prompt_layer_sum```, are there no parameters involved in the training?
I found that using the ```self.weight= torch.nn.Parameter(torch.Tensor(2, 2))```, but those parameters not be involved with any other tensor about input or template.

Thanks!

**Comment by Starlien95** [comment]
"graph_prompt_layer_sum" is an ablation study. For graph level task, the prompt should be set as "FEATURE-WEIGHTED-SUM".

**Comment by jiaruHithub** [comment]
Thank u!
