### ISSUE TITLE
您好，我想请教代码中数据预处理部分

### ISSUE THREAD

**Issue by ShenzhiYang2000** [Starlien95/GraphPrompt#4]
大佬您好，请问代码中数据集中的raw等文件夹中预处理过的数据是怎么处理的呢，我好像没有从代码中找到这一部分处理数据集的代码。
比如下图中ENZYMES文件夹下的all, allraw, nodefewshot以及raw文件夹中的数据是怎么生成的呢？特别是raw文件夹在代码中被直接使用了。上面的BZR，COX2等数据集我从开源处下载下来其中没有这些文件夹。

<img width="393" alt="graphprompt" src="https://user-images.githubusercontent.com/73417792/229806324-cd694e1d-50b7-47bc-8d10-c67f2ce940f6.png">
如果是代码中有相关代码，可以帮忙指出吗😂；如果没有，可以分享一下吗😀

Thanks！

**Comment by gongchenghua** [comment]
您好呀，我也在follow graphprompt 的工作，可以留个联系方式交流一下吗

> 大佬您好，请问代码中数据集中的raw等文件夹中预处理过的数据是怎么处理的呢，我好像没有从代码中找到这一部分处理数据集的代码。 比如下图中ENZYMES文件夹下的all, allraw, nodefewshot以及raw文件夹中的数据是怎么生成的呢？特别是raw文件夹在代码中被直接使用了。上面的BZR，COX2等数据集我从开源处下载下来其中没有这些文件夹。
> 
> <img alt="graphprompt" width="393" src="https://user-images.githubusercontent.com/73417792/229806324-cd694e1d-50b7-47bc-8d10-c67f2ce940f6.png">
> 
> 如果是代码中有相关代码，可以帮忙指出吗😂；如果没有，可以分享一下吗😀
> Thanks！

**Comment by Starlien95** [comment]
感谢您对graphprompt的关注，我将在4.25号前把数据数据处理部分整合到github代码中

**Comment by Starlien95** [comment]
感谢您对graphprompt的关注，我将在4.25号前把数据处理部分整合到github上

**Comment by gongchenghua** [comment]
> 感谢您对graphprompt的关注，我将在4.25号前把数据处理部分整合到github上

大佬我有一些代码上的问题想要请教，可以留个邮箱嘛

**Comment by Starlien95** [comment]
论文里的邮箱就可以联系我

**Comment by gongchenghua** [comment]
> 论文里的邮箱就可以联系我

已经发邮件给你啦，大佬！

**Comment by gongchenghua** [comment]
已经发邮件啦，大佬



---原始邮件---
发件人: "Xingtong ***@***.***&gt;
发送时间: 2023年4月18日(周二) 晚上8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Starlien95/GraphPrompt] 您好，我想请教代码中数据预处理部分 (Issue #4)




 
论文里的邮箱就可以联系我

**Comment by Starlien95** [comment]
生成raw文件的代码已经上传

**Comment by Starlien95** [comment]
生成raw文件的代码已经上传

**Comment by WxxShirley** [comment]
> 大佬您好，请问代码中数据集中的raw等文件夹中预处理过的数据是怎么处理的呢，我好像没有从代码中找到这一部分处理数据集的代码。 比如下图中ENZYMES文件夹下的all, allraw, nodefewshot以及raw文件夹中的数据是怎么生成的呢？特别是raw文件夹在代码中被直接使用了。上面的BZR，COX2等数据集我从开源处下载下来其中没有这些文件夹。
> 
> <img alt="graphprompt" width="393" src="https://user-images.githubusercontent.com/73417792/229806324-cd694e1d-50b7-47bc-8d10-c67f2ce940f6.png">
> 
> 如果是代码中有相关代码，可以帮忙指出吗😂；如果没有，可以分享一下吗😀
> Thanks！

Can you successfully run the code, i.e, reproducing the results reported in the original paper? I just found that running currently released code without any revision would obtain extraordinarily better performance on graph classification task and N/A on node classification task?

**Comment by WxxShirley** [comment]
> 您好呀，我也在follow graphprompt 的工作，可以留个联系方式交流一下吗
> 
> > 大佬您好，请问代码中数据集中的raw等文件夹中预处理过的数据是怎么处理的呢，我好像没有从代码中找到这一部分处理数据集的代码。 比如下图中ENZYMES文件夹下的all, allraw, nodefewshot以及raw文件夹中的数据是怎么生成的呢？特别是raw文件夹在代码中被直接使用了。上面的BZR，COX2等数据集我从开源处下载下来其中没有这些文件夹。
> > <img alt="graphprompt" width="393" src="https://user-images.githubusercontent.com/73417792/229806324-cd694e1d-50b7-47bc-8d10-c67f2ce940f6.png">
> > 如果是代码中有相关代码，可以帮忙指出吗😂；如果没有，可以分享一下吗😀
> > Thanks！

Can you successfully run the code, i.e, reproducing the results reported in the original paper? I just found that running currently released code without any revision would obtain extraordinarily better performance on graph classification task and N/A on node classification task?

**Comment by gongchenghua** [comment]
我的微信18362968765可以劳烦你加一下吗哈哈



---原始邮件---
发件人: "Xixi ***@***.***&gt;
发送时间: 2023年7月4日(周二) 中午12:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Starlien95/GraphPrompt] 您好，我想请教代码中数据预处理部分 (Issue #4)




  
您好呀，我也在follow graphprompt 的工作，可以留个联系方式交流一下吗
  
大佬您好，请问代码中数据集中的raw等文件夹中预处理过的数据是怎么处理的呢，我好像没有从代码中找到这一部分处理数据集的代码。 比如下图中ENZYMES文件夹下的all, allraw, nodefewshot以及raw文件夹中的数据是怎么生成的呢？特别是raw文件夹在代码中被直接使用了。上面的BZR，COX2等数据集我从开源处下载下来其中没有这些文件夹。
 
 如果是代码中有相关代码，可以帮忙指出吗😂；如果没有，可以分享一下吗😀
 Thanks！
   
Can you successfully run the code, i.e, reproducing the results reported in the original paper? I just found that running currently released code without any revision would obtain extraordinarily better performance on graph classification task and N/A on node classification task?
