### ISSUE TITLE
Questions about GraphPrompt Implementation

### ISSUE THREAD

**Issue by WxxShirley** [Starlien95/GraphPrompt#5]
I have just read your paper GraphPrompt. It is really impressive and well-done!
However, I do have some questions regarding the implementation and results.

* **Datasets**: In the current Github repository, only the ENZYMES dataset is available. Could you please advise on how to access the other raw datasets?
* **Implementation Details**: I am curious about the necessity of writing the Sampler class in your implementation. Does it have a significant impact on the overall performance?
* **Experiments**: After downloading your current code and running it on my machine, I discovered that the accuracy for the graph classification task on the ENZYMES dataset is 0.4965 (5-shot setting), which is *significantly better* than the results reported in your original paper. I am quite confused as I have not made any changes to your original methods, and these results seem *unbelievably good*.

I understand that you may have a busy schedule, and my questions may seem trivial.
Nevertheless, I greatly appreciate any insights or clarifications you can provide. 
Thank you in advance for your time and attention!

**Comment by Starlien95** [comment]
1.Since the original data format of the TUdataset is the same, you can refer to convertor/ENZYMES.py to process other datasets.
2.The Sampler does not have a significant improvement on performance. This class was used in the code of my previous work, and the code of this work inherits the content of the previous code, so the sampler is retained.
3.This is acceptable, since the results are  related to the machine used in the experiment and the random seed. Due to the few-shot experiment, the randomness will be great.

**Comment by WxxShirley** [comment]
Thank you so much for your patience and reply! I really appreciate your time and help.
However, I still have another small question. 
When running the node classification task (after running graph classification task) as `python run.py` under the `nodedownstream` folder, the results are all **nan** since the prompt vector becomes **nan**.I am wondering how to avoid such scenario?

**Comment by Starlien95** [comment]
I have never encountered this situation. The prompt vector as a trainable variable should not have a nan value. But if you encounter it, I suggest you can try to normalize the prompt vector.

**Comment by WxxShirley** [comment]
Got it! Thank you so much : )

**Comment by gqq1210** [comment]
> Thank you so much for your patience and reply! I really appreciate your time and help. However, I still have another small question. When running the node classification task (after running graph classification task) as `python run.py` under the `nodedownstream` folder, the results are all **nan** since the prompt vector becomes **nan**.I am wondering how to avoid such scenario?

I didn't change the source code, but I ran into the same problem. How can I solve it ?

**Comment by Starlien95** [comment]
I have never encountered this situation, I suspect it may be related to the random seed. I suggest you gradually output the value of the prompt vector and observe when the prompt vector becomes nan. The problem is likely to be solved by normalizing the prompt vector.

**Comment by gqq1210** [comment]
> I have never encountered this situation, I suspect it may be related to the random seed. I suggest you gradually output the value of the prompt vector and observe when the prompt vector becomes nan. The problem is likely to be solved by normalizing the prompt vector.

Thanks! I will try it. Btw, in the code of `prompt_fewshot.py` and `run.py`, the parameter `c_embedding` passed in is not used when evaluating (`def evaluate`), but `c_embedding` is recalculated through the node_label of val/test (`c_embedding = center_embedding(embedding, node_label, label_num,debug)`). Does this introduce ground_truth?
Maybe I misunderstood, looking forward to your reply！

**Comment by Starlien95** [comment]
> > I have never encountered this situation, I suspect it may be related to the random seed. I suggest you gradually output the value of the prompt vector and observe when the prompt vector becomes nan. The problem is likely to be solved by normalizing the prompt vector.
> 
> Thanks! I will try it. Btw, in the code of `prompt_fewshot.py` and `run.py`, the parameter `c_embedding` passed in is not used when evaluating (`def evaluate`), but `c_embedding` is recalculated through the node_label of val/test (`c_embedding = center_embedding(embedding, node_label, label_num,debug)`). Does this introduce ground_truth? Maybe I misunderstood, looking forward to your reply！

The ground truth is the prototype embedding of each class used for similarity comparison. Even so, I will implement this part of the code in a clearer way in the new version.

**Comment by MahmoudZamani** [comment]
Hello Xington, Hope you are doing well and thank you for making the project available. Is the below screenshot showing the same issue that other user mentioned? Any help appreciated!
![GP-issue-1](https://github.com/Starlien95/GraphPrompt/assets/6118316/11273c6b-4f94-4bd0-9b66-47d43a70eee6)

**Comment by MahmoudZamani** [comment]
> Hello Xington, Hope you are doing well and thank you for making the project available. Is the below screenshot showing the same issue that other user mentioned? Any help appreciated! ![GP-issue-1](https://user-images.githubusercontent.com/6118316/254633855-11273c6b-4f94-4bd0-9b66-47d43a70eee6.JPG)

Even when I used my own datasets, I don't know why it's not training anymore.

![GP-issue-2](https://github.com/Starlien95/GraphPrompt/assets/6118316/b94ba238-bcbc-40d6-a733-51171efc2772)

**Comment by Starlien95** [comment]
> > Hello Xington, Hope you are doing well and thank you for making the project available. Is the below screenshot showing the same issue that other user mentioned? Any help appreciated! ![GP-issue-1](https://user-images.githubusercontent.com/6118316/254633855-11273c6b-4f94-4bd0-9b66-47d43a70eee6.JPG)
> 
> Even when I used my own datasets, I don't know why it's not training anymore.
> 
> ![GP-issue-2](https://user-images.githubusercontent.com/6118316/254634665-b94ba238-bcbc-40d6-a733-51171efc2772.JPG)

I think the loss is decreasing, but it is not shown due to the number of decimal places printed. I suggest you set more decimal places for print.

**Comment by MahmoudZamani** [comment]
Hello Xington,
It did not help me, and I still got the similar results (increased 10 and16 ->25). Any other suggestion? That would be great if I could give you a demo and talk about my dataset. Please let me know your thoughts. Then if we could fix the bug(s), no one will get similar issues.

Thanks

![GP-issue-3](https://github.com/Starlien95/GraphPrompt/assets/6118316/4891f499-196d-4e93-8f21-6c3ebe2e8ee6)

**Comment by Starlien95** [comment]
> Hello Xington, It did not help me, and I still got the similar results (increased 10 and16 ->25). Any other suggestion? That would be great if I could give you a demo and talk about my dataset. Please let me know your thoughts. Then if we could fix the bug(s), no one will get similar issues.
> 
> Thanks
> 
> ![GP-issue-3](https://user-images.githubusercontent.com/6118316/254794034-4891f499-196d-4e93-8f21-6c3ebe2e8ee6.JPG)

I am not sure if this is the same issue the other users mention. I need more information to figure out where the problem lies. I suggest you output the values of the prompt vector and embedding in each epoch to see their changes.

**Comment by Starlien95** [comment]
One of my juniors told me that he also encountered the issue of the prompt vector being nan, and his solution is as follows: The encounter with nan occurred when running on a 2080Ti, and the problem was solved when he switched to an A100. I think it's because some operations in the code involved GPU precision.

**Comment by gqq1210** [comment]
> One of my juniors told me that he also encountered the issue of the prompt vector being nan, and his solution is as follows: The encounter with nan occurred when running on a 2080Ti, and the problem was solved when he switched to an A100. I think it's because some operations in the code involved GPU precision.

Thanks for your answer. Hope you can provide other solutions if it is convenient. It will help us a lot~

**Comment by SwaggyZhang** [comment]
> Hello Xington, Hope you are doing well and thank you for making the project available. Is the below screenshot showing the same issue that other user mentioned? Any help appreciated! ![GP-issue-1](https://user-images.githubusercontent.com/6118316/254633855-11273c6b-4f94-4bd0-9b66-47d43a70eee6.JPG)

I have the same problem on the RTX 3090.
