### ISSUE TITLE
How can I generate the ENZYMESGraphClassification and ENZYMEPreTrain files for my datasets?

### ISSUE THREAD

**Issue by MahmoudZamani** [Starlien95/GraphPrompt#6]
Hello 

Thank you for being responsible regarding to the issues happening to other users of your code.
I was wondering if you could explain about the generating ENZYMESGraphClassification and ENZYMEPreTrain files. I want to use other datasets, but I couldn't figure out where are the scripts. I only have datasets looks like TUDataset. Really appreciate even If someone else have used the code and can respond to the question. 

Look forward to hearing from you,
Best

**Comment by Starlien95** [comment]
You can refer to the code in convertor/ENZYMES.py to convert the data of TUdataset into inputs that can be used for code execution.

**Comment by gqq1210** [comment]
Hello
When I run `nodedownstream/pre_train.py` ,I get the following problem `FileNotFoundError: [Errno 2] No such file or directory: '../data/debug/graphs'`.
It seems that the data set is not provided. How is the data set here made? Is there any processing file similar to `convertor/ENZYMES.py`?
Look forward to hearing from you,
Best

**Comment by Starlien95** [comment]
> Hello When I run `nodedownstream/pre_train.py` ,I get the following problem `FileNotFoundError: [Errno 2] No such file or directory: '../data/debug/graphs'`. It seems that the data set is not provided. How is the data set here made? Is there any processing file similar to `convertor/ENZYMES.py`? Look forward to hearing from you, Best

Node tasks and graph tasks use the same pre-training model. The pre-training code is in graphdownstream. So there is no need to pre-train in nodedownstream again.
