### ISSUE TITLE
A problem about the graph class prototype

### ISSUE THREAD

**Issue by SONGLEI-arch** [Starlien95/GraphPrompt#7]
Hello, I am very interested in your paper, but I have a small problem with the calculation of graph class prototypes. The calculation of the graph class prototype in your code is done in a batch. If the batch size is set to a small value, will the calculation of the graph class prototype be inaccurate? Looking forward to your answer to this question, thank you!

**Comment by Starlien95** [comment]
It won't have an impact, because our downstream tasks are inherently few-shot, and the number of samples is very likely not to exceed the batch size.
